travis:
  secure:
    BINSTAR_TOKEN: 0lrIWwLT3VwamPwtAhrPR/yRqAHPCZ46BY25GJ1y1VdFsn7pbj9fAwRMT1WueezkNY4f5Ug2+voignCztsMVBaRBlEBQIVkbFDsZf4z6MVR6xiOz2ZjVq4VlFuvcIpRraJo/99O6Wyb6xNKj9PGbvAP4H1VjcF9nVzJUPYPkMnrGr+ka/tgwFoG8LFOWA4AtvuUR6QLHQariSzjNKRVDVPNmsGoVeSdof7A7QH8bxysPMZS/soLFN7WxkYWOdxr9R17eeofnoTAZ2YeFkmMiRnawH73siCYjXrgY6Fpgvjm6SAb84Qrh1bThccb3FoTa7bz2YZXoGqDSS+kMkqUrq9FSl8ACdnEMh2qy/vIwFMPkBzlLrQ6k2+dtQAuXpM41A+KwioCSff4zSwz8wsbknAnyrRhK2d0D2oFWdZB+l07Yujh6dcHtAIy9MlipvqUvBXkr3Orv0XkCRPevJR5VHE5NWPmkL8FMlOZj8SBR0OwccypkvPy4KKO8t+p7DLoYYabMe9ZGi7qTeRdul9f7MCi6PrRyfODrmmdtV7hQgLmRj6a50XMYXRrjvtewol9n9KPNZbQDOXh+fbyXvJiaPnVWJKsIVEvAOTin8ch16yp+cA3hetuEubcDqh65oichD5JXyNOzanLjWy2ZnTz1gb15syZ7fz3Fu6j5G9RMKGU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
